### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by silidev** [hardmooth/wikidpad2markdown#6]
Thanks for your great tool! 

I wont need it, but maybe for future users somebody might want to catch this:

```
2024-03-08 17:51:59,082 [ERROR] UNCAUGHT EXCEPTION
Traceback (most recent call last):
  File "L:\Dropbox\ObsImported\wikidpad2markdown.py", line 421, in <module>
    RunMain()
  File "L:\Dropbox\ObsImported\wikidpad2markdown.py", line 348, in RunMain
    wiki_content = fh.read()
                   ^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 90: invalid start byte
Traceback (most recent call last):
  File "L:\Dropbox\ObsImported\wikidpad2markdown.py", line 421, in <module>
    RunMain()
  File "L:\Dropbox\ObsImported\wikidpad2markdown.py", line 348, in RunMain
    wiki_content = fh.read()
                   ^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 90: invalid start byte
```

Workaround: Convert to the offending files to UTF-8,

**Comment by HartmutLeister** [comment]
Thank you @silidev for the bug report.
I will take a look in my next dev session.

What file was this run on?
Was this one of my sample pages or one you supplied? (if the latter: please add it here)

**Comment by hardmooth** [comment]
I propose the following fixes (for non utf8 files)

* Raise an error, if `--strict` (bonus: give a good hint on the offending line)
* Convert with "replace" to utf8, then continue (bonus: write to log)

**Comment by silidev** [comment]
Yes, sounds great to me :)

Am So., 28. Juli 2024 um 21:00 Uhr schrieb Hartmut Leister <
***@***.***>:
